public Class A0123
{
public Account createAccount(String name)  //method to create account
{
//Test comment for Account 1
//Test comment for Account 2
//Test comment for Account 2
//Test comment for Account 2//Test comment for Account 2
//Test comment for Account 2
//Test comment for Account 2//Test comment for Account 2
//Test1niwienw
//Test comment for Account 2
//Test comment for Account 2//Test comment for Account 2
//Test comment for Account 2
//Test comment for Account 2//Test comment for Account 2
//Test1niwienw
Account a01123 = new Account();
a01123 .Name = name;
return a01123 ;
//this is the test comment
//Test112345
}
}