public Class A025
{
public Account createAccount(String name)  //method to create account
{
//test edit comment for Account A0
//saikumar test mar20
Account a02511 = new Account();
a02511 .Name = name;

Account a02512 = new Account();
Account a02513 = new Account();


//a02512 .Name1 = text;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
return a02511 ;
}
}