public Class A026
{
public Account createAccount(String name)  //method to create account
{

Account a02611 = new Account();
Account a02612 = new Account();
a02611 .Name = name;
return a02611 ;
//atoz
//divya
//sai
//ratna
//vasanth
//saivbv
//this is the test comment
//saivbv
//this is the test comment
//saivbv
//this is the test comment
//saivbv
//this is the test comment
//saivbv
//this is the test comment
//saivbv
//this is the test comment
}
}