public Class A12
{
public Account createAccount(String name)  //method to create account
{
//Add Comment for A12
Account a1211222 = new Account();
Account a1212 = new Account();
Account a121133224999 = new Account();
Account a1211339999 = new Account();
Account a12113300224444 = new Account();
Account a121133002211 = new Account();
//a1211.Name = name;
return a1211222;
//this is the test comment1
//sai
}
}