public Class A1234
{
public Account createAccount(String name)  //method to create account
{
//test edit comment for Account A0
//saikumar test mar20
Account a1234= new Account();
a1234.Name = name;

Account a02512 = new Account();
Account a02513 = new Account();
Account a02514 = new Account();
Account a02515 = new Account();

//a02512 .Name1 = text;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02512 .Name1 = text;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
return a1234;
}
}