public Class A15
{
public Account createAccount(String name)  //method to create account
{
//test edit comment for Account A0
//saikumar test mar20
Account a02511 = new Account();
Account a02521 = new Account();
Account a02522 = new Account();
Account a02523 = new Account();
Account a02525 = new Account();
Account a02529 = new Account();
Account a02520 = new Account();

a02511 .Name = name;
return a02511 ;
//sai
//this is the test comment
//sampath new comment
}
}