public Class A19
{
public Account createAccount(String name)  //method to create account
{
//Add comment for Account A19
Account a19a = new Account();
a19a.Name = name;
return a19a;
//this is the test comment
//a02512 .Name1 = text;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
}
}