public Class A21
{
public Account createAccount(String name)  //method to create Test
{
//Change from demo one second time123 12 
//Demo one
Account acc12 = new Account();
Account acc13 = new Account();
Account acc14 = new Account();
acc12.Name = name;
//Demo one
return acc12;
//Demo one
//a02512 .Name1 = text;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20//a02512 .Name1 = text;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
}
}