public Class AFocus_ServicesFutureService
{
public Account createAccount(String name)  //method to create account
{
//Add Comment for A12
Account a1211 = new Account();
Account a1212 = new Account();
Account a121133224 = new Account();
Account a121133 = new Account();
Account a1211330022 = new Account();
Account a121133002211 = new Account();
 System.debug('>>>>>>>>>>>>>>>>>>>>>');
 System.debug('>>>>>>>>>>>>>>>>>');
a1211.Name = name;
return a1211;
//this is the test comment1
//sai
}
}