public Class ARTest1
{
public Account createAccount(String name)  //testing
{
//by sai

//Vishal
Account acc122 = new Account();
acc122.Name = name;
return acc122;
//this is the test comment
//a02512 .Name1 = text;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02512 .Name1 = text;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02512 .Name1 = text;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
//a02511 .Name = name;
//return a02511 ;
//test edit comment for Account A0
//saikumar test mar20
}
}