public Class CITest1
{
public Account createAccount(String name)  //method to create account
{
//Add Comment for A12
Account a12111122 = new Account();

Account a12111122FFDSF = new Account();
Account a121111224 = new Account();
Account a1211112243 = new Account();
Account a12111122E = new Account();
Account a12111122R = new Account();
Account a121111223 = new Account();
Account a12111122D = new Account();
Account a121111222 = new Account();
Account a12111122Q = new Account();
Account a121111227 = new Account();
Account a1211112243QQWQ = new Account();
Account a1211112254 = new Account();
Account a1211112232 = new Account();
Account a121111221222 = new Account();
Account a12111122K = new Account();
Account a12111122Af = new Account();
Account a12111122ew= new Account();
Account a12111122wqa = new Account();
Account a12111122afe = new Account();
Account a12111122fa = new Account();
Account a12111122saf = new Account();
Account a12111122afSAAAAA = new Account();
Account a12111122afeWWWWWWWWWWWWW = new Account();
Account a12111122AE = new Account();
Account a12111122EEWR = new Account();

//this is the test comment1
//maruthi comment updated
//additional comment
//new comment
return a12111122;
}
}