public Class febTwelve
{
public Account createAccount(String name)  //method to create account
{
//Modify
Account an034112111= new Account();

an034112111.Name = name;
//Modify11111114512311
//maven4 Modify
return an034112111;
//Sai test67
//saoijsaojs
//abcd456
//567rftyuioplkjhgf
//saoijsaojs
//abcd456
//567rftyuioplkjhgf
//Modify11111114512311
//maven4 Modify
//Modify111111145123111
//maven4 Modify skippped
//Modify111111145123111
//maven4 Modify skippped
}
}