public Class juneTweleve
{
public Account createAccount(String name)  //method to create account
{
//Modify1
Account ad112112= new Account();

ad112112.Name = name;
//Modify111111145123
//saoijsaojs
//abcd456
//567rftyuioplkjhgf
//saoijsaojs
//abcd456
//Add comment for Account A1
//Add comment for Account A1
//567rftyuioplkjhgf
//saoijsaojs
//abcd456
//567rftyuioplkjhgf
//saoijsaojs
//abcd456
//567rftyuioplkjhgf
//saoijsaojs
//abcd456
//567rftyuioplkjhgf
//maven4 Modify
return ad112112;
//sai
}
}