public Class NewApex
{
public Account createAccount(String name)  //method to create account12
{
//Test comment for Account 1
//Test1niwienw
Account a01123 = new Account();
Account a01129 = new Account();
Account a01128 = new Account();


a01123 .Name = name;
//Test comment for Account 1
//Test1niwienw
return a01123 ;
//this is the test comment
//Test comment for Account 1
//Test comment for Account 1
//Test1niwienw
//Test112345
//this is the test comment
//Test comment for Account 1
//Test comment for Account 1
//Test1niwienw
//Test112345
//this is the test comment
//Test comment for Account 1
//Test comment for Account 1
//Test1niwienw
//Test112345
//this is the test comment
//Test comment for Account 1
//Test comment for Account 1
//Test1niwienw
//Test112345
//this is the test comment
//Test comment for Account 1
//Test comment for Account 1
//Test1niwienw
//Test112345
}
}